-- Current sql file was generated after introspecting the database
-- If you want to run this migration please uncomment this code before executing migrations
/*
CREATE TABLE "post" (
	"date" timestamp with time zone DEFAULT now() NOT NULL,
	"author" varchar NOT NULL,
	"title" varchar,
	"image" text,
	"avatar" text,
	"description" text,
	"id" text PRIMARY KEY NOT NULL
);
--> statement-breakpoint
ALTER TABLE "post" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "user" (
	"seq" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "user_seq_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"name" varchar NOT NULL,
	"password" varchar,
	"avatar" text,
	"email" varchar,
	"id" varchar,
	CONSTRAINT "user_password_key" UNIQUE("password")
);
--> statement-breakpoint
CREATE POLICY "Enable insert for authenticated users only" ON "post" AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK (true);--> statement-breakpoint
CREATE POLICY "Enable read access for all users" ON "post" AS PERMISSIVE FOR SELECT TO public;
*/